name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    uses: stylelint/.github/.github/workflows/lint.yml@34f1c0ac91f245ee4ee5ce725bb844328c17ccf5 # 0.3.0
    permissions:
      contents: read

  test:
    uses: stylelint/.github/.github/workflows/test.yml@34f1c0ac91f245ee4ee5ce725bb844328c17ccf5 # 0.3.0
    with:
      node-version: '["20", "22", "24"]'
    permissions:
      contents: read
